nelmio_api_doc:
    documentation:
        info:
            title: Stackoverflow API Proxy
            description: Search for questions in stackoverflow
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
